### ISSUE TITLE
GitHub link

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/epiforecasts.github.io#13]
Should the GitHub link in the top right corner link to https://github.com/epiforecasts instead of https://github.com/epiforecasts/epiforecasts.github.io? Similarly, one could question whether we need a separate Software page or should just link to the GitHub (downside of linking to GitHub: we can only pin 6 repos).

**Comment by sbfnk** [comment]
Perhaps a good solution for the Software page would be to pull GitHub links + descriptions from a curated list (which could be longer than 6)?

**Comment by Bisaloo** [comment]
I like the idea of having a software page where we list re-usable projects / libraries. Our GitHub is much more messy and contains papers, code for papers, etc.

My current idea is to automatically generate the software page from the contents of our r-universe.
