### ISSUE TITLE
Embed twitter posts from epiforecasts

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epiforecasts.github.io#18]
This might be nice as dynamic content but also might be more trouble than its worth.

**Comment by Bisaloo** [comment]
https://help.twitter.com/en/using-twitter/embed-twitter-feed

**Comment by Bisaloo** [comment]
![image](https://user-images.githubusercontent.com/10783929/151933470-629747ed-1067-4a71-91f1-527ebd8f87c8.png)

?

**Comment by sbfnk** [comment]
Looks good to me!
