### ISSUE TITLE
Add DOI to blog posts

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/epiforecasts.github.io#27]

**Comment by sbfnk** [comment]
Do you know what needs doing to be able to do this?

**Comment by Bisaloo** [comment]
As far as I know, there is no standard way to do it. 

The best option would be to cross-post the posts on Zenodo or OSF and get the DOI from there. It wouldn't link directly to the epiforecasts website though.

**Comment by sbfnk** [comment]
I don't think I'd want to live with the weight of responsibility of maintaining the epiforecasts web site forever because a DOI links to it! I think your suggestion is a good one (figshare might be another option)

**Comment by Bisaloo** [comment]
https://github.com/ropenscilabs/deposits/issues/19

**Comment by sbfnk** [comment]
Now done via https://rogue-scholar.org/
