### ISSUE TITLE
Add goatcounter

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/epiforecasts.github.io#32]
It would be good to be able to track visitors - in the forecast/scenario hubs we've had good experience with https://www.goatcounter.com/ (which doesn't require cookies).

**Comment by Bisaloo** [comment]
Seems like https://epiforecasts.goatcounter.com already exists. I don't remember creating it. Did you?

**Comment by sbfnk** [comment]
No, but my login works for it so I must have had this brilliant idea before and subsequently forgotten about it. I think you should have admin rights too. 

All we need to do is add this javaScript snippet: https://epiforecasts.goatcounter.com/help/start

**Comment by sbfnk** [comment]
which we have here:
https://github.com/epiforecasts/epiforecasts.github.io/blob/main/header.html 

but it's not used by quarto?
