### ISSUE TITLE
Twitter feed very narrow

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/epiforecasts.github.io#37]
Seeing this in both Firefox/Chrome

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1156307/186398400-fb2afd3a-b886-4aca-8b56-235dfd48c8b0.png">

**Comment by Bisaloo** [comment]
I can reproduce although interestingly, it is fixed if I resize my browser window after loading the page.

**Comment by sbfnk** [comment]
closed by #67
